/**
 * Build supabase/seed-local.sql: Massachusetts and Boston sample data for local
 * development and the demo, plus two example discussions.
 *
 *   npm run load-districts && npm run job -- boston --since 2026-07-01   # real Boston data
 *   npx tsx scripts/make-local-seed.ts --people <openstates/people>/data/ma/legislature
 *
 * Sources: Boston rows are read back from the local database after a real sync
 * (Legistar, no key); districts come from the simplified Analyze Boston fixture;
 * Massachusetts legislators come from the public-domain openstates/people repo
 * (the same data Open States serves). Massachusetts bills need an Open States key
 * and are not included.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import postgres from 'postgres';
import { parse as parseYaml } from 'yaml';

type Value = string | number | boolean | null | undefined;

function lit(value: Value | Date): string {
  if (value === null || value === undefined) return 'null';
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${value.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, Value | Date>[]): string {
  if (rows.length === 0) return '';
  const cols = Object.keys(rows[0]!);
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n');
  return `insert into public.${table} (${cols.join(', ')}) values\n${values};\n\n`;
}

const { values } = parseArgs({
  options: {
    people: { type: 'string' },
    matters: { type: 'string', default: '40' },
    out: { type: 'string', default: 'supabase/seed-local.sql' },
  },
});

const sql = postgres(process.env.SUPABASE_DB_URL ?? 'postgresql://postgres:postgres@127.0.0.1:54322/postgres', {
  max: 1,
  onnotice: () => undefined,
});

const out: string[] = [
  '-- Massachusetts and Boston sample data. Generated by scripts/make-local-seed.ts; do not edit by hand.\n\n',
];

// ---- Boston council districts (simplified to ~20 m) ------------------------
const geo = JSON.parse(
  readFileSync(
    new URL('../packages/congress-client/test/fixtures/legistar/council-districts-simplified.geojson', import.meta.url),
    'utf8',
  ),
) as { features: { properties: Record<string, unknown>; geometry: unknown }[] };
for (const f of geo.features) {
  const district = Number(f.properties.DISTRICT ?? f.properties.District ?? f.properties.district);
  out.push(
    `insert into public.council_districts (city, district, name, geometry, source) values ('ma-boston', ${district}, ${lit(
      `District ${district}`,
    )}, extensions.st_multi(extensions.st_setsrid(extensions.st_geomfromgeojson(${lit(JSON.stringify(f.geometry))}), 4326)), 'Analyze Boston, City Council Districts 2023-2032 (simplified)');\n`,
  );
}
out.push('\n');

// ---- Boston council (from a real Legistar sync) ------------------------------
const officials = await sql`select * from public.local_officials where city = 'ma-boston' order by id`;
const matters = await sql`
  select * from public.local_matters where city = 'ma-boston'
   order by latest_action_date desc nulls last, last_modified desc limit ${Number(values.matters)}`;
const ids = matters.map((m) => m.id as string);
const actions =
  await sql`select * from public.local_matter_actions where matter_id in ${sql(ids)} order by matter_id, seq`;
const sponsors =
  await sql`select * from public.local_matter_sponsors where matter_id in ${sql(ids)} order by matter_id, sequence`;
const meetings = await sql`select * from public.local_meetings where city = 'ma-boston' order by date desc limit 12`;
if (officials.length === 0 || matters.length === 0) throw new Error('No Boston data: run the boston job first.');

const strip = (rows: Record<string, unknown>[], drop: string[] = []) =>
  rows.map(
    (r) => Object.fromEntries(Object.entries(r).filter(([k]) => !drop.includes(k))) as Record<string, Value | Date>,
  );
const asDate = (rows: Record<string, Value | Date>[], cols: string[]) =>
  rows.map((r) => {
    for (const c of cols) if (r[c] instanceof Date) r[c] = (r[c] as Date).toISOString().slice(0, 10);
    return r;
  });

out.push(insert('local_officials', asDate(strip(officials), ['start_date', 'end_date'])));
out.push(
  insert(
    'local_matters',
    asDate(strip(matters, ['search']), ['intro_date', 'agenda_date', 'passed_date', 'latest_action_date']),
  ),
);
out.push(insert('local_matter_actions', asDate(strip(actions), ['action_date'])));
out.push(insert('local_matter_sponsors', strip(sponsors)));
out.push(insert('local_meetings', asDate(strip(meetings), ['date'])));

// ---- Massachusetts legislators (openstates/people, public domain) -----------
interface Person {
  id: string;
  name: string;
  email?: string;
  image?: string;
  party?: { name: string; end_date?: string }[];
  roles?: { type: string; district: string; end_date?: string }[];
  links?: { url: string }[];
}
if (values.people) {
  const rows = readdirSync(values.people)
    .filter((f) => f.endsWith('.yml'))
    .map((f) => parseYaml(readFileSync(join(values.people!, f), 'utf8')) as Person)
    .map((p) => {
      const role = p.roles?.find((r) => !r.end_date && (r.type === 'upper' || r.type === 'lower'));
      if (!role) return null;
      return {
        id: p.id,
        name: p.name,
        party: p.party?.find((x) => !x.end_date)?.name ?? null,
        state: 'MA',
        chamber: role.type,
        district: role.district,
        title: role.type === 'upper' ? 'Senator' : 'Representative',
        photo_url: p.image ?? null,
        email: p.email ?? null,
        openstates_url: p.links?.find((l) => l.url.includes('malegislature.gov'))?.url ?? null,
        current: true,
      };
    })
    .filter((r): r is NonNullable<typeof r> => r !== null)
    .sort((a, b) => a.id.localeCompare(b.id));
  out.push(insert('state_legislators', rows));
  console.log(`MA legislators: ${rows.length}`);
}

// ---- Example discussions -------------------------------------------------------
const exampleMatter = matters.find((m) => /ordinance/i.test(String(m.type))) ?? matters[0]!;
out.push(
  insert('discussions', [
    {
      id: 'example-boston-ordinance',
      title: `Example: what should the City Council weigh on Docket #${exampleMatter.file_number}?`,
      prompt: `This is an example discussion for local development. Docket #${exampleMatter.file_number}: ${String(exampleMatter.title).slice(0, 400)}\n\nWhat matters most to you about this proposal? Vote on the statements and add your own.`,
      jurisdiction: 'ma-boston',
      district: null,
      target_type: 'local_matter',
      target_id: exampleMatter.id as string,
      status: 'open',
      residency_required: true,
    },
    {
      id: 'example-federal-hr1',
      title: 'Example: what should Congress consider about H.R. 1?',
      prompt:
        'This is an example discussion for local development. H.R. 1 in the 119th Congress is a large budget reconciliation bill.\n\nWhat should lawmakers weigh most? Vote on the statements and add your own.',
      jurisdiction: 'federal',
      district: null,
      target_type: 'bill',
      target_id: '119-hr-1',
      status: 'open',
      residency_required: false,
    },
  ]),
);

writeFileSync(values.out!, out.join(''));
console.log(
  `Wrote ${values.out}: ${officials.length} councilors, ${matters.length} matters, ${actions.length} actions, ${sponsors.length} sponsors, ${meetings.length} meetings`,
);
await sql.end();
